# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Dylan Folsom
tagline:          'Personal Website'
description:      'Ph.D. Student at the Princeton University <a href="https://phy.princeton.edu" target="_blank">Department of Physics</a>.'
url:              https://fongandrew.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

# paginate:         5
# paginate_path:    '/prelims/:num'


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
