# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Dylan Folsom
tagline:          'Personal Website'
description:      'Ph.D. Candidate at the Princeton University <a href="https://phy.princeton.edu" target="_blank">Department of Physics</a>.'
url:              https://dfolsom.com
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Dylan Folsom'
  url:            https://github.com/folsomde

# paginate:         5
# paginate_path:    '/prelims/:num'


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-redirect-from

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
exclude: 
  - _exclude/
  - Gemfile*
  - .git/
  - .git*
  - .obsidian/
  - README.md
  - jekyll-theme-hydeout.gemspec
  - site.webmanifest