metadata = {
"J00E1": ["A Two-Wire Transmission Line",	["Capacitors"]],
"J00E2": ["Pitching Pennies into a Magnet",	["Induction"]],
"J00E3": ["A Phased Antenna Array",	["Radiation"]],
"J00M1": ["Shape of an Arch",	["Continuous Media"]],
"J00M2": ["Linked Rods Falling",	["Lagrangian Mechanics"]],
"J00M3": ["Orbiting Mass on a String",	["Central Force Motion"]],
"J00Q1": ["Scattering From a Central Potential",	["Quantum Scattering"]],
"J00Q2": ["Two Interacting Particles",	["Perturbation Theory"]],
"J00Q3": ["Electron on a Ring",	["Eigenstates"]],
"J00T1": ["Ideal Gas In a Magnetic Field",	["Magnetic Fields"]],
"J00T2": ["Masses on a Piston of Gas",	["Gas in Container"]],
"J00T3": ["Bose-Einstein Condensation by Evaporation",	["Bose-Einsten Condensation"]],
"J01E1": ["Resistance Between Two Points on a Disk",	["Induction"]],
"J01E2": ["Betatron",	["EM Waves"]],
"J01E3": ["Electromagnetic Wave on a Slab of Dielectric",	["Small Oscillations"]],
"J01M1": ["Particle on a Torus",	["Rigid Body Motion"]],
"J01M2": ["Free Precession of a Planet - 1",	["Rigid Body Motion"]],
"J01M3": ["Free Precession of a Planet - 2",	["Perturbation Theory"]],
"J01Q1": ["Excitation of a Harmonic Oscillator",	["1D QM"]],
"J01Q2": ["Scattering From Two Delta-function Potentials",	["TDPT"]],
"J01Q3": ["Spin in a Magnetic Field",	["Gas in Container"]],
"J01T1": ["Containers of Ideal Gas",	["Chemical Potential"]],
"J01T2": ["Solution of Biomolecules",	["Ising Model"]],
"J01T3": ["Triangular Chain Ising Model",	["Waveguides and Cavities"]],
"J02E1": ["Coaxial Transmission Line",	["Induction"]],
"J02E2": ["Rotating Dielectric Cylinder",	["EM Fields in Matter"]],
"J02E3": ["Levitating Frog",	["Central Force Motion"]],
"J02M1": ["Flapping Toy",	["Continuous Media"]],
"J02M2": ["Slingshot Orbit",	["Eigenstates"]],
"J02M3": ["Stretching Cable",	["Misc Quantum"]],
"J02Q1": ["Particle in a Spherically Symmetric Potential",	["Perturbation Theory"]],
"J02Q2": ["Wave Functions and Coordinate Frames",	["Gas in Container"]],
"J02Q3": ["Interacting Particles on a Line",	["Van der Waals Gas"]],
"J02T1": ["Joule-Thomson Process",	["Magnetic Fields"]],
"J02T2": ["Neutrons in a Magnetic Field",	["Fermi Gas"]],
"J02T3": ["Ensemble of Harmonic Oscillators",	["Chemical Potential"]],
"J03E1": ["Waves in Aluminum",	["Oscillators"]],
"J03E2": ["Image Charges",	["EM Waves"]],
"J03E3": ["Rotating Charged Rod",	["Method of Images"]],
"J03M1": ["Scattering from an Attractive Potential",	["Radiation"]],
"J03M2": ["Disk with Three Springs",	["Small Oscillations"]],
"J03M3": ["Orbits in a Central Potential",	["Classical Scattering"]],
"J03Q1": ["Central Potential Scattering",	["Normal Modes"]],
"J03Q2": ["Hydrogen Atom Transitions",	["Central Force Motion"]],
"J03Q3": ["Nuclear Alpha Decay",	["Quantum Scattering"]],
"J03T1": ["Container of Gases",	["TDPT"]],
"J03T2": ["Krypton Molecule Formation",	["Spin"]],
"J03T3": ["Spin Gas in a Magnetic Field",	["Gas in Container"]],
"J04E1": ["Rotating Cylindrical Capacitor",	["Misc Statmech"]],
"J04E2": ["Mass Spectrometer",	["Magnetic Fields"]],
"J04E3": ["Thomson Scattering",	["Capacitors"]],
"J04M1": ["Bead on a Wire",	["Radiation"]],
"J04M2": ["Power Law Central Force",	["Central Force Motion"]],
"J04M3": ["Falling Stick",	["Rigid Body Motion"]],
"J04Q1": ["Arbitrary Potential",	["Misc Quantum"]],
"J04Q2": ["Boosted Wave Function",	["Misc Quantum"]],
"J04Q3": ["Spin in a Magnetic Field",	["TDPT"]],
"J04T1": ["Non-interacting Spins",	["Magnetic Fields"]],
"J04T2": ["Fermionic Gas",	["Fermi Gas"]],
"J04T3": ["DNA as a Polymer Chain",	["Polymers"]],
"J05E1": ["Spherical Half-Filled Capacitor",	["Curvilinear Coordinates", "Capacitors"]],
"J05E2": ["Light Incident on a Medium",	["EM Waves"]],
"J05E3": ["Dielectric Sphere in a Laser Beam",	["EM Fields in Matter"]],
"J05M1": ["Rope Around a Cylinder",	["Friction"]],
"J05M2": ["Planet Moving Through Dust Cloud",	["Classical Scattering"]],
"J05M3": ["Waves in a Series of Pendula",	["Oscillators"]],
"J05Q1": ["Fermion Entanglemen",	["Misc Quantum"]],
"J05Q2": ["Charged Particle on a Ring",	["Perturbation Theory"]],
"J05Q3": ["Heavy Particle Passing a Hydrogen Atom",	["TDPT"]],
"J05T1": ["Polymer Chain",	["Polymers"]],
"J05T2": ["Bose Einstein Condensation",	["Bose-Einsten Condensation"]],
"J05T3": ["Thermodynamic Variables",	["Misc Statmech"]],
"J06E1": ["Dielectric Cylinder in an Electric Field",	["Curvilinear Coordinates"]],
"J06E2": ["Half Rings of Magnetic Material",	["Magnetostatics"]],
"J06E3": ["Harmonic Oscillator Radiation",	["Radiation"]],
"J06M1": ["Gyroscope",	["Rigid Body Motion", "Small Oscillations"]],
"J06M2": ["Displaced Circular Orbit",	["Central Force Motion"]],
"J06M3": ["Bead on a Rotating Wire",	["Small Oscillations"]],
"J06Q1": ["Position and Momentum",	["untagged"]],
"J06Q2": ["Two Indistinguishable Bosons",	["1D QM"]],
"J06Q3": ["Magnetic Resonance",	["TDPT"]],
"J06T1": ["Bose Einstein Condensation",	["untagged"]],
"J06T2": ["Liquid-Gas Phase Transition",	["Phase Transitions"]],
"J06T3": ["DNA Molecule",	["Polymers"]],
"J07E1": ["Point Charge and Conducting Sphere",	["Method of Images"]],
"J07E2": ["Rotating Shell of Charge",	["Curvilinear Coordinates"]],
"J07E3": ["Negative Dielectric Constant",	["EM Waves"]],
"J07M1": ["Ball on a Turntable",	["Rolling Constraints"]],
"J07M2": ["Inverted T Pendulum",	["Normal Modes"]],
"J07M3": ["Bubble in an Incompressible Fluid",	["Fluid Mechanics"]],
"J07Q1": ["Excitation from a Delta Function Potential",	["1D QM"]],
"J07Q2": ["Effective Mass",	["1D QM"]],
"J07Q3": ["Triangular Molecule",	["Misc Quantum"]],
"J07T1": ["Dilute Ionized Hydrogen",	["Hydrogen Formation"]],
"J07T2": ["Diatomic Gas in an Electric Field",	["Diatomic Gas in E-Fields"]],
"J07T3": ["Spin Waves",	["Waves"]],
"J08E1": ["Radiation from an Antenna",	["Magnetic Vector Potential"]],
"J08E2": ["Rotating Disk in a Magnet",	["Radiation"]],
"J08E3": ["Parallel Plate Diode",	["Induction"]],
"J08M1": ["Pendulum on a Sled",	["Lagrangian Mechanics"]],
"J08M2": ["Sphere in a Pipe",	["Small Oscillations"]],
"J08M3": ["Fluid Flow",	["Fluid Mechanics"]],
"J08Q1": ["Deuteron",	["Eigenstates"]],
"J08Q2": ["Spin in a Magnetic Field",	["TDPT"]],
"J08Q3": ["Photoelectric Effect",	["EM in QM"]],
"J08T1": ["Graphene",	["Fermi Gas"]],
"J08T2": ["Spin Gas",	["Fermi Gas"]],
"J08T3": ["Motion of a Bead",	["Brownian Motion"]],
"J09E1": ["Motion in EM Fields",	["untagged"]],
"J09E2": ["Ion Source",	["Capacitors"]],
"J09E3": ["Magnetic Pressure",	["Magnetostatics"]],
"J09M1": ["Coupled Pendula",	["Normal Modes"]],
"J09M2": ["Minimizing Drag",	["Continuous Media"]],
"J09M3": ["Falling Rod",	["Misc Mechanics"]],
"J09Q1": ["Dressed States and Rabi Oscillation",	["TDPT"]],
"J09Q2": ["Scattering an Electron from a Step in the magnetic field",	["EM in QM"]],
"J09Q3": ["Trapping Atoms in an Optical Lattice",	["Misc Quantum"]],
"J09T1": ["The Partition Function",	["Misc Statmech"]],
"J09T2": ["Defects in a Lattice",	["untagged"]],
"J09T3": ["Errors in Gene Expression",	["Misc Statmech"]],
"J10E1": ["Oscillating Dipole Near a Conducting Plane",	["Method of Images"]],
"J10E2": ["Rotating Sphere in a Magnetic Field",	["EM Fields in Matter"]],
"J10E3": ["Rectangular Waveguide",	["Waveguides and Cavities"]],
"J10M1": ["Rod on a Rail",	["Lagrangian Mechanics"]],
"J10M2": ["Orbiting Mass on a String",	["Central Force Motion"]],
"J10M3": ["Slab on Rotating Rollers",	["Friction"]],
"J10Q1": ["Harmonic Oscillator",	["QHO"]],
"J10Q2": ["Angular Momentum",	["Spin"]],
"J10Q3": ["Spin-Dependent Scattering",	["Quantum Scattering"]],
"J10T1": ["Graphene",	["Fermi Gas"]],
"J10T2": ["Maxwell-Boltzmann Gas",	["Misc Statmech"]],
"J10T3": ["Thermodynamics of Superconductors",	["Phase Transitions"]],
"J11E1": ["Coaxial Waveguide",	["Waveguides and Cavities"]],
"J11E2": ["Beam of charged Particles",	["EM Fields in Matter"]],
"J11E3": ["Current-carrying cylinder",	["Magnetostatics"]],
"J11M1": ["Lasso",	["Rigid Body Motion"]],
"J11M2": ["Rolling Coin",	["Rigid Body Motion"]],
"J11M3": ["Double Pendulum",	["Normal Modes"]],
"J11Q1": ["Quantum Zeno Effect",	["Misc Quantum"]],
"J11Q2": ["1D Well",	["Perturbation Theory"]],
"J11Q3": ["Positronium",	["Eigenstates"]],
"J11T1": ["Atmosphere's Adiabatic lapse rate",	["Altitude"]],
"J11T2": ["Hydrogen's two spin isomers",	["Phase Transitions"]],
"J11T3": ["Ice skating",	["Chemical Potential", "Phase Transitions"]],
"J12E1": ["Laplace's equation",	["Capacitors"]],
"J12E2": ["Waves in Plasma",	["EM Waves"]],
"J12E3": ["Particle above a superconductor",	["Magnetostatics"]],
"J12M1": ["Ant on a ring",	["Rigid Body Motion"]],
"J12M2": ["Paper towel roll",	["Rigid Body Motion"]],
"J12M3": ["Spinning Bucket",	["Non-Inertial Reference Frames"]],
"J12Q1": ["Time-dependent perturbation theory",	["TDPT"]],
"J12Q2": ["System of two spin one-half particles",	["Eigenstates"]],
"J12Q3": ["Particle around a solenoid",	["EM in QM"]],
"J12T1": ["Fermi gas",	["Fermi Gas"]],
"J12T2": ["Ising model",	["Ising Model"]],
"J12T3": ["Heat engine",	["Heat Engines", "Phase Transitions"]],
"J13E1": ["Field Transformations",	["Magnetostatics"]],
"J13E2": ["Radiating Fields",	["Radiation"]],
"J13E3": ["Complex Impedances",	["Induction"]],
"J13M1": ["Coriolis Effect",	["Non-Inertial Reference Frames"]],
"J13M2": ["Higgs Orbits",	["Central Force Motion"]],
"J13M3": ["Precession of Equinoxes",	["Central Force Motion"]],
"J13Q1": ["Wavepackets",	["1D QM"]],
"J13Q2": ["Indistinguishable particles",	["Eigenstates"]],
"J13Q3": ["Distinguishable particles",	["Eigenstates"]],
"J13T1": ["DNA Molecule",	["Polymers"]],
"J13T2": ["Fermi gas",	["Fermi Gas"]],
"J13T3": ["Superconducting phase transition",	["Phase Transitions"]],
"J14E1": ["Magnetized Cylinder",	["EM Fields in Matter"]],
"J14E2": ["Particle on a loop",	["Induction"]],
"J14E3": ["Wave incident on a medium",	["EM Waves"]],
"J14M1": ["Orbiting mass",	["Central Force Motion"]],
"J14M2": ["Precession of the Earth",	["untagged"]],
"J14M3": ["Small Oscillations",	["untagged"]],
"J14Q1": ["Bound States",	["untagged"]],
"J14Q2": ["Scattering from a Spherical Potential",	["untagged"]],
"J14Q3": ["Harmonic Oscillator coupled to a spin one-half particle",	["untagged"]],
"J14T1": ["Fluctuations of a liquid",	["Misc Statmech"]],
"J14T2": ["Fermi gas",	["Fermi Gas"]],
"J14T3": ["Polymers",	["Polymers"]],
"J15E1": ["Magnetic moment through a loop",	["Induction"]],
"J15E2": ["Fresnel rhomb",	["EM Waves"]],
"J15E3": ["Mass spec",	["Magnetostatics"]],
"J15M1": ["Precession due to the sun's oblateness",	["Central Force Motion"]],
"J15M2": ["Frequencies and normal modes",	["Normal Modes"]],
"J15M3": ["Rolling with and without slipping",	["Rolling Constraints"]],
"J15Q1": ["Helium",	["Eigenstates"]],
"J15Q2": ["Hydrogen transitions",	["TDPT"]],
"J15Q3": ["Arbitrary potential",	["untagged"]],
"J15T1": ["The weather underground",	["Altitude"]],
"J15T2": ["Atmospheric Density",	["Misc Statmech"]],
"J15T3": ["An ideal Bose gas",	["Bose-Einsten Condensation"]],
"J16E1": ["Conducting plane with bulge",	["untagged"]],
"J16E2": ["Long Antenna Pattern",	["untagged"]],
"J16E3": ["Slicing a Waveguide",	["untagged"]],
"J16M1": ["Rotating Crankshaft",	["untagged"]],
"J16M2": ["Disc on Springs",	["untagged"]],
"J16M3": ["Orbiting Beer Can",	["untagged"]],
"J16Q1": ["Perturbed Harmonic Oscillator",	["untagged"]],
"J16Q2": ["Decay Angular Correlations",	["untagged"]],
"J16Q3": ["Magnetic Barrier",	["untagged"]],
"J16T1": ["String Thermodynamics",	["untagged"]],
"J16T2": ["Ideal Gas with Funny Dispersion Relation",	["untagged"]],
"J16T3": ["Hydrogen Recombination",	["untagged"]],
"J17E1": ["Magnetic Levitation",	["untagged"]],
"J17E2": ["Coaxial cable",	["untagged"]],
"J17E3": ["Waveguide transmitter",	["untagged"]],
"J17M1": ["Coupled pendulums",	["untagged"]],
"J17M2": ["Viscous flow",	["untagged"]],
"J17M3": ["Orbits in a cone",	["untagged"]],
"J17Q1": ["Interacting spins",	["untagged"]],
"J17Q2": ["s-wave scattering resonances",	["untagged"]],
"J17Q3": ["Perturbed Hydrogen Atom",	["untagged"]],
"J17T1": ["Atomic Molecular Gas",	["untagged"]],
"J17T2": ["Liquid-Gas Critical Point",	["untagged"]],
"J17T3": ["Protein folding",	["untagged"]],
"J18E1": ["Faraday Effect Polarizer",	["untagged"]],
"J18E2": ["Image Problems",	["untagged"]],
"J18E3": ["Dealing with Stress",	["untagged"]],
"J18M1": ["Stablized Instability",	["untagged"]],
"J18M2": ["Making Waves",	["untagged"]],
"J18M3": ["Doomsday Scenario",	["untagged"]],
"J18Q1": ["Two Hydrogen Atoms",	["untagged"]],
"J18Q2": ["Tunneling Under A Sloping Barrier",	["untagged"]],
"J18Q3": ["White Dwarf Star",	["untagged"]],
"J18T1": ["Particles in a Box",	["untagged"]],
"J18T2": ["Hawking radiation",	["untagged"]],
"J18T3": ["Particles on a Line",	["untagged"]],
"J98E1": ["Electromagnetic Wave Incident on a Lossy Dielectric",	["EM Waves"]],
"J98E2": ["Rotating Charged Rod",	["Curvilinear Coordinates"]],
"J98E3": ["Conducting Hemispheres",	["Continuous Media"]],
"J98M1": ["Hanging Rope",	["Normal Modes"]],
"J98M2": ["Pucks on a Spring",	["Rolling Constraints"]],
"J98M3": ["Ice Skate",	["Perturbation Theory"]],
"J98Q1": ["Parity Violation",	["1D QM"]],
"J98Q2": ["Two Delta-function Potential",	["Spin"]],
"J98Q3": ["Hyperfine Structure",	["Misc Statmech"]],
"J98T1": ["Quark-Antiquark Pairs",	["Chemical Potential"]],
"J98T2": ["Cooling Liquid Helium",	["Phase Transitions"]],
"J98T3": ["Spins in a Magnetic Field",	["Magnetic Fields"]],
"J99E1": ["Charged Particle Trap",	["EM Waves"]],
"J99E2": ["Transverse Momentum from an Electromagnetic Wave",	["EM Waves"]],
"J99E3": ["Magnetic Field at a Pulsar",	["Radiation"]],
"J99M1": ["Rolling Disk",	["Lagrangian Mechanics"]],
"J99M2": ["Particle Rolling on a Hyperboloid",	["Central Force Motion"]],
"J99M3": ["Rod Orbiting the Sun",	["Atomic QM"]],
"J99Q1": ["Hydrogen Molecule",	["Spin"]],
"J99Q2": ["Spins on a Square",	["TDPT"]],
"J99Q3": ["Electron Transition out of a Square Well",	["Chemical Potential"]],
"J99T1": ["Weirdons",	["Phase Transitions"]],
"J99T2": ["Maxwell Construction",	["Misc Statmech"]],
"J99T3": ["Ice Making Machine",	["untagged"]],
"M00E1": ["Emitted Flux Density",	["EM Waves"]],
"M00E2": ["Particle Above a Conducting Plane",	["Radiation", "Method of Images"]],
"M00E3": ["Toroidal Solenoids",	["Induction"]],
"M00M1": ["Precession of the Perihelion",	["Central Force Motion"]],
"M00M2": ["Ladder on a Wall",	["Misc Mechanics"]],
"M00M3": ["Bead on a Hoop",	["Small Oscillations"]],
"M00Q1": ["Harmonic Oscillator in a Magnetic Field",	["Perturbation Theory"]],
"M00Q2": ["Hyperfine Structure",	["Spin"]],
"M00Q3": ["Emission of Alpha Particles",	["Spin"]],
"M00T1": ["Distillation",	["Phase Transitions"]],
"M00T2": ["Brownian Motion",	["Brownian Motion"]],
"M00T3": ["Defects in a Crystal",	["Crystal Lattice"]],
"M01E1": ["Non-parallel Plate Capacitor",	["Capacitors"]],
"M01E2": ["Radio Waves in a Gas of Charged Particles",	["EM Waves"]],
"M01E3": ["Charged Rotating Cylindrical Shells",	["Induction"]],
"M01M1": ["Massive Spring",	["Continuous Media"]],
"M01M2": ["Particle in an Anharmonic Potential",	["Misc Mechanics"]],
"M01M3": ["Particle in Gravitational and Magnetic Fields",	["Friction"]],
"M01Q1": ["The Berry Phase",	["Misc Quantum"]],
"M01Q2": ["Two Hydrogen Atoms",	["Atomic QM"]],
"M01Q3": ["Transmission Through a Grid",	["Quantum Scattering"]],
"M01T1": ["Measuring Fundamental Constants",	["Misc Statmech"]],
"M01T2": ["Polymer Chain",	["Polymers"]],
"M01T3": ["Electron Gas in a Magnetic Field",	["Magnetic Fields"]],
"M02E1": ["Iron Ring with a Gap",	["Magnetostatics"]],
"M02E2": ["Dielectric Cylinder in an Electric Field",	["EM Fields in Matter"]],
"M02E3": ["Current in a Cylindrical Wire",	["Magnetostatics"]],
"M02M1": ["Particle in a Cone",	["Lagrangian Mechanics"]],
"M02M2": ["Mass on a String",	["Normal Modes"]],
"M02M3": ["The Coriolis Effect",	["Non-Inertial Reference Frames"]],
"M02Q1": ["Driven Harmonic Oscillator",	["QHO"]],
"M02Q2": ["Three Particles on a Ring",	["Eigenstates"]],
"M02Q3": ["Scattering From a Magnetic Barrier",	["EM in QM"]],
"M02T1": ["Dilute Gas in Gravity",	["Gas in Container"]],
"M02T2": ["Hydrogen Formation",	["Hydrogen Formation"]],
"M02T3": ["Pauling’s Ice Rule",	["Phase Transitions"]],
"M03E1": ["Force Between Current Carrying Wires",	["Magnetic Vector Potential"]],
"M03E2": ["The Method of Images",	["Method of Images"]],
"M03E3": ["Electromagnetic Wave in a Plasma",	["EM Waves"]],
"M03M1": ["Lagrange points and WMAP",	["Central Force Motion"]],
"M03M2": ["Rolling Sphere",	["Rolling Constraints"]],
"M03M3": ["Helmholtz Resonator",	["Oscillators"]],
"M03Q1": ["Flipping Spins With a Magnetic Field",	["TDPT"]],
"M03Q2": ["Scattering From a Central Potential",	["Quantum Scattering"]],
"M03Q3": ["Addition of Angular Momentum",	["Spin", "Eigenstates"]],
"M03T1": ["Thermodynamics of an Elastic String",	["Misc Statmech"]],
"M03T2": ["White Dwarf Star",	["Fermi Gas"]],
"M03T3": ["Particles in a Box",	["Gas in Container"]],
"M04E1": ["Conducting Sphere Coated with Dielectric",	["Curvilinear Coordinates"]],
"M04E2": ["Classical Radiation from a Hydrogen Atom",	["Radiation"]],
"M04E3": ["Penny Thrown into a Solenoid",	["Induction"]],
"M04M1": ["Particles on a Line",	["Misc Mechanics"]],
"M04M2": ["Coupled Pendula",	["Normal Modes"]],
"M04M3": ["Panels in Space",	["Rigid Body Motion"]],
"M04Q1": ["Hydrogen Molecule",	["Atomic QM"]],
"M04Q2": ["Positronium in a Magnetic Field",	["Spin"]],
"M04Q3": ["Scattering from a Cube Potential",	["Quantum Scattering"]],
"M04T1": ["Equations of State",	["Heat Engines"]],
"M04T2": ["Surface Waves and Heat Capacity",	["Waves"]],
"M04T3": ["Binary Mixture of Atoms",	["Particles on a Line"]],
"M05E1": ["Periodic Surface Charge and Magnetization",	["EM Fields in Matter"]],
"M05E2": ["Coaxial Cable Motion",	["Waveguides and Cavities"]],
"M05E3": ["Electron Orbit Decay",	["Radiation"]],
"M05M1": ["Vibration Damping With a Piston",	["Oscillators"]],
"M05M2": ["Suspension Bridge Shape",	["Continuous Media"]],
"M05M3": ["Satellite Orientation",	["Central Force Motion"]],
"M05Q1": ["Hydrogen Atom in an Electric Field",	["TDPT"]],
"M05Q2": ["Delta Function Potential",	["Quantum Scattering"]],
"M05Q3": ["Nitrogen and Explosive",	["untagged"]],
"M05T1": ["Thermodynamics of Solid Argon",	["Fermi Gas"]],
"M05T2": ["Defects in a Cubic Crystal",	["Crystal Lattice"]],
"M05T3": ["Surface Waves and Heat Capacity",	["Waves"]],
"M06E1": ["Metal Sphere in a Uniform Electric Field",	["Curvilinear Coordinates"]],
"M06E2": ["Superconducting Loop",	["Induction"]],
"M06E3": ["Radiation from a Falling Electron",	["Radiation"]],
"M06M1": ["Point Mass in a Sphere",	["untagged"]],
"M06M2": ["Huygens’ Pendulum",	["Lagrangian Mechanics"]],
"M06M3": ["Hanging Spring",	["Continuous Media"]],
"M06Q1": ["One-dimensional Wave Function",	["1D QM"]],
"M06Q2": ["EPR Beam Splitter",	["Misc Quantum"]],
"M06Q3": ["Two Interacting Particles",	["1D QM"]],
"M06T1": ["Interacting Particles on a Line",	["Particles on a Line"]],
"M06T2": ["Diatomic Gas in an Electric Field",	["Diatomic Gas in E-Fields"]],
"M06T3": ["Boson Surface Absorption",	["Bose-Einsten Condensation"]],
"M07E1": ["Point Charge an Conducting Sphere",	["Method of Images"]],
"M07E2": ["Noise in a Circular Ring",	["untagged"]],
"M07E3": ["Plane Wave in a Conductor",	["EM Waves"]],
"M07M1": ["Planetary Orbits",	["Central Force Motion"]],
"M07M2": ["Particle in an Ellipsoid",	["untagged"]],
"M07M3": ["Mass on a Massive String",	["Oscillators"]],
"M07Q1": ["Quantum Virial Theorem",	["Misc Quantum"]],
"M07Q2": ["Scattering",	["Quantum Scattering"]],
"M07Q3": ["Delta Function in a Box",	["Perturbation Theory"]],
"M07T1": ["Pions",	["Phase Transitions"]],
"M07T2": ["Soap Film",	["Heat Engines"]],
"M07T3": ["3D Ising Model",	["Ising Model", "Phase Transitions"]],
"M08E1": ["Wiggler",	["untagged"]],
"M08E2": ["Accelerating Point Charge",	["Radiation"]],
"M08E3": ["Electromagnet with an Iron Core",	["Magnetostatics"]],
"M08M1": ["Bead on a Hoop",	["Small Oscillations"]],
"M08M2": ["Springs and Blocks",	["Normal Modes"]],
"M08M3": ["Gravitational Capture of Dark Matter Particles",	["Central Force Motion"]],
"M08Q1": ["Delta Function Potential",	["1D QM"]],
"M08Q2": ["Ladder Operators",	["QHO"]],
"M08Q3": ["Dynamics of Spin",	["Spin"]],
"M08T1": ["Brownian Motion",	["Brownian Motion"]],
"M08T2": ["van der Waals Gas",	["Van der Waals Gas"]],
"M08T3": ["Electrons Escaping Metal",	["Fermi Gas"]],
"M09E1": ["Cavity Dynamics",	["Waveguides and Cavities"]],
"M09E2": ["Pulsar",	["untagged"]],
"M09E3": ["Charge and Conducting Sphere",	["Method of Images"]],
"M09M1": ["Bubble in an Incompressible Fluid",	["Fluid Mechanics"]],
"M09M2": ["Shape of a Suspended Rope",	["Continuous Media"]],
"M09M3": ["Automobile Crankshaft",	["Misc Mechanics"]],
"M09Q1": ["Hydrogen Beam",	["Perturbation Theory"]],
"M09Q2": ["Dynamics of Spin one-half Particles",	["Spin"]],
"M09Q3": ["Pion-Atom Scattering",	["Quantum Scattering"]],
"M09T1": ["Ideal Gas in an Electric Field",	["Diatomic Gas in E-Fields"]],
"M09T2": ["Particles on a Line",	["Crystal Lattice", "Particles on a Line"]],
"M09T3": ["2D and 3D Bosons",	["Chemical Potential"]],
"M10E1": ["Birefringent material",	["EM Fields in Matter"]],
"M10E2": ["Square loop antenna",	["Magnetic Vector Potential"]],
"M10E3": ["Torque produced by an AC induction motor",	["Induction"]],
"M10M1": ["Bead sliding on a rotating wire",	["Small Oscillations"]],
"M10M2": ["Rope friction",	["Friction"]],
"M10M3": ["Space hotel",	["Rigid Body Motion"]],
"M10Q1": ["Energy of a large atom",	["Eigenstates"]],
"M10Q2": ["Anharmonic Oscillator",	["Perturbation Theory"]],
"M10Q3": ["Hyperfine Splittings",	["Spin"]],
"M10T1": ["One-dimensional model for rubber",	["Polymers"]],
"M10T2": ["Thermionic emission of electrons from a metal surface",	["Fermi Gas"]],
"M10T3": ["Van der Waals equation",	["Van der Waals Gas"]],
"M12E1": ["Cylinder in a Magnetic Field",	["Induction"]],
"M12E2": ["Thomson Scattering",	["Radiation"]],
"M12E3": ["Bent wire loop",	["Magnetic Vector Potential"]],
"M12M1": ["Beam on posts",	["Oscillators"]],
"M12M2": ["Washer",	["Rigid Body Motion"]],
"M12M3": ["Dryer",	["Rigid Body Motion"]],
"M12Q1": ["Scattering",	["Quantum Scattering"]],
"M12Q2": ["Tritium",	["Atomic QM"]],
"M12Q3": ["Spin system",	["Eigenstates"]],
"M12T1": ["Temperature cycle",	["Altitude"]],
"M12T2": ["Heat engine",	["Heat Engines"]],
"M12T3": ["Ferromagnet",	["Misc Statmech"]],
"M13Q1": ["Hyperfine Structure",	["Spin"]],
"M13Q2": ["Delta function potential",	["TDPT"]],
"M13Q3": ["Spins on a square",	["Spin"]],
"M13T1": ["Carnot Engine",	["untagged"]],
"M13T2": ["Graphene",	["untagged"]],
"M13T3": ["Frustrated and Unfrustrated Magnetism",	["untagged"]],
"M15E1": ["Radiating Charge",	["Radiation"]],
"M15E2": ["Periodic Charge",	["EM Fields in Matter"]],
"M15E3": ["Shielding",	["untagged"]],
"M15M1": ["Rolling Sphere",	["Small Oscillations"]],
"M15M2": ["Attractive Central Force",	["Central Force Motion"]],
"M15M3": ["Unicycle",	["Rigid Body Motion"]],
"M15Q1": ["Delta function potential",	["1D QM"]],
"M15Q2": ["Particle in an electric field",	["QHO"]],
"M15Q3": ["Yukawa scattering",	["Quantum Scattering"]],
"M15T1": ["Spin trimers",	["Ising Model"]],
"M15T2": ["Piston",	["Van der Waals Gas"]],
"M15T3": ["Adiabatic demagnetization",	["Magnetic Fields"]],
"M17E1": ["Plasma Waves",	["untagged"]],
"M17E2": ["Moving Bar Magnet",	["untagged"]],
"M17E3": ["Spinning Cylinder",	["untagged"]],
"M17M1": ["Dark Matter",	["untagged"]],
"M17M2": ["Falling Rod",	["untagged"]],
"M17M3": ["Disk with Three Springs",	["untagged"]],
"M17Q1": ["Atom in a Cavity",	["untagged"]],
"M17Q2": ["Squeezing the Harmonic Oscillator",	["untagged"]],
"M17Q3": ["Tritium Beta Decay",	["untagged"]],
"M17T1": ["Putting Pressure on 3-He",	["untagged"]],
"M17T2": ["Surface Adsorption",	["untagged"]],
"M17T3": ["Photon Condensate",	["untagged"]],
"M18E1": ["Space charge",	["untagged"]],
"M18E2": ["Mechanical Radio Station",	["untagged"]],
"M18E3": ["Dielectric Cylinder in an Electric Field",	["untagged"]],
"M18M1": ["Planetary Slingshot",	["untagged"]],
"M18M2": ["Particle in Cone",	["untagged"]],
"M18M3": ["Space Panels",	["untagged"]],
"M18Q1": ["Hydrogen Molecule",	["untagged"]],
"M18Q2": ["Flipping a spin",	["untagged"]],
"M18Q3": ["Low-energy scattering",	["untagged"]],
"M18T1": ["Interstitials and Vacancies",	["untagged"]],
"M18T2": ["Brownian Motion",	["untagged"]],
"M18T3": ["Distillation",	["untagged"]],
"M98E1": ["Field of a Wire",	["Magnetic Vector Potential"]],
"M98E2": ["Cylindrical Magnet and a Steel Sheet",	["EM Fields in Matter"]],
"M98E3": ["Magnetic Field of the Earth",	["Radiation"]],
"M98M1": ["Mass on a Rope and Cylinder",	["Rolling Constraints", "Friction"]],
"M98M2": ["Masses Connected by a Spring",	["Normal Modes"]],
"M98M3": ["Fluid Dynamics",	["Fluid Mechanics"]],
"M98Q1": ["Two Interacting Particles",	["Spin"]],
"M98Q2": ["Scattering From a Spherical Potential",	["Quantum Scattering"]],
"M98Q3": ["Variational Principle",	["Misc Quantum"]],
"M98T1": ["Carnot Engine",	["Heat Engines"]],
"M98T2": ["Helium Atoms in a Box",	["Gas in Container"]],
"M98T3": ["Anharmonic Oscillator",	["Oscillators"]],
"M99E1": ["Radiation from a Rotating Sphere",	["Radiation"]],
"M99E2": ["5-Spoke Wheel",	["Induction"]],
"M99E3": ["Dielectric Cylinder",	["EM Fields in Matter"]],
"M99M1": ["Ball Rolling in a Cylinder",	["Rolling Constraints"]],
"M99M2": ["Two Repulsive Particles",	["Classical Scattering"]],
"M99M3": ["Drum Head",	["Continuous Media"]],
"M99Q1": ["Interacting Magnetic Dipoles",	["Spin"]],
"M99Q2": ["Excited States of Helium",	["Atomic QM"]],
"M99Q3": ["Beam Me Up, Charlie",	["Misc Quantum"]],
"M99T1": ["The Otto Cycle",	["Heat Engines"]],
"M99T2": ["Polymer Chain",	["Polymers"]],
"M99T3": ["Surface Waves",	["Waves"]],
}


nl='\n'

for y in range(21):
	year = 1998+y
	for m in ["01", "05"]:
		mlett = "J" if m == "01" else "M"
		for snum, s in enumerate(['M','E', 'Q', 'T']):
			subject = {'E': 'E&M', 'M':'Mechanics', 'T': 'Statmech', 'Q': 'QM'}[s]
			for i in range(3):
				problem = i+1
				pstring = f"{mlett}{year%100:02d}{s}{problem}"
				if pstring in metadata:
					file = open(f'./_posts/problems/{year}-{m}-{13-(3*snum+problem)}-{s}{problem}-{metadata[pstring][0].replace(" ", "-") if pstring in metadata else "NEED-TITLE"}.md','w')
					file.write(f'''---
title: "{pstring} &ndash; {metadata[pstring][0] if pstring in metadata else "NEED TITLE"}"
layout: post
categories:
  - Prelims
  - Problems
tags:
  - {subject}
  - {mlett}{year%100:02d}
{''.join(['  - '+tag+nl for tag in metadata[pstring][1]])}
permalink: /:categories/:year/:month/{s}{problem}:output_ext
comments: false
---
<object data="{year}{mlett}{problem}{s}.pdf" type="application/pdf" width="100%" height="500"></object>
<div class="message"><a href='https://princetonprelim.com/prelim/{2*y+(0 if m == '01' else 1)}/'>Check for solutions to this year's exam</a></div>''')
